### PR TITLE
cellsize required

### PR DESCRIPTION
**Pull request by TariqBlecher**

### CODE REVIEW

**Comment by gijzelaerr** [comment]
can you rebase this in one commit?

**Comment by TariqBlecher** [comment]
Sorry I'm not sure what you mean, should I build the repo again and make the commits?

**Comment by gijzelaerr** [comment]
ah never mind. You can rewrite the history, so this `meqform.py` doesn't appear in the history. I'll do this.

**Comment by gijzelaerr** [comment]
rebased commits and merged

https://github.com/ska-sa/rodrigues/commit/1b27ceebe3c74dd9223cc0cad2872e3ed4675a8a

**Pull request closed without merging**
